name: Check

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
      - run: npm run check
      - run: npm run package:firefox
      - run: npm run package:chrome
      - run: python3 -m zipfile -t dist/twitch-vod-muted-skipper-firefox.zip
      - run: python3 -m zipfile -t dist/twitch-vod-muted-skipper-chrome.zip
      - run: npx --yes web-ext@10.6.0 lint --source-dir dist/firefox
